name = "ReplGPT"
uuid = "8ef5fce9-1516-4e06-b171-18cb54ddb04b"
authors = ["Thatcher Chamberlin <j.thatcher.c@gmail.com>"]
version = "0.1.0"

[deps]
Markdown = "d6f4376e-aef5-505a-96c1-9c027394607a"
OpenAI = "e9f21f70-7185-4079-aca2-91159181367c"
Preferences = "21216c6a-2e73-6563-6e65-726566657250"
ReplMaker = "b873ce64-0db9-51f5-a568-4457d8e49576"

[compat]
Markdown = "1.6"
OpenAI = "0.6"
ReplMaker = "0.2"
julia = "1.6"
